title: Kevin Raymond
description: Writing about sheet metal, HVAC, work, and whatever else I'm paying attention to.
url: "https://kesm89.github.io"
baseurl: "/kevinraymond"
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
future: false
show_excerpts: true
timezone: America/New_York

author:
  name: Kevin Raymond

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
